### ISSUE TITLE
Spinedit

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_pep8#7]
ширину надо больше на 10-15 пк (Lin font),
минимум дан 80, а как задать 78?

**Comment by kvichans** [comment]
"78" извращение - его можно руками в ini задать

**Comment by Alexey-T** [comment]
79 же нормально.

**Comment by kvichans** [comment]
ОК. Мне никогда не приходилось пользоваться этим ограничением. Что задать для spinedit? 30,200,1?

**Comment by Alexey-T** [comment]
минимум 70... Шаг лучше 1

**Comment by kvichans** [comment]
70,200,1?

**Comment by Alexey-T** [comment]
Да

**Comment by kvichans** [comment]
ok

**Comment by Alexey-T** [comment]
Из-за оч длинных строк лучше так, 70,2000,1

**Comment by kvichans** [comment]
Да ну? Это же только "сообщалка", а не "резалка". 
Отнесу к разряду извращений - оставлю 200

**Comment by Alexey-T** [comment]
Лучше 500
